### ISSUE TITLE
libuv dependency

### ISSUE THREAD

**Issue by juliangruber** [clibs/net#2]
Shouldn't libuv be installed thorugh clibs?

Besides that, looks awesome!

**Comment by yorkie** [comment]
Thank you, @juliangruber, and this work could be a little bit hard to me, unless we have a copy of libuv and added a `package.json` for clib, but it has been in TODO list of this repo.

:)

**Comment by stephenmathieson** [comment]
Can we fork libuv into the clibs name?  We've already done this for a few packages ([cutef8](https://github.com/clibs/cutef8), [linenoise](https://github.com/clibs/linenoise), ...)

**Comment by yorkie** [comment]
I'm totally agreed on this.

**Comment by jwerle** [comment]
Hmm do we really want to start adopting forks as clibs? Are we going to constantly pull from upstream to maintain changes from joyent/libuv ?

**Comment by juliangruber** [comment]
component does the same for big ones and it seems to work and helps transition to a more modular system

**Comment by jwerle** [comment]
Yeah, that is true

**Comment by yorkie** [comment]
seems fixed with https://github.com/clibs/net/commit/03882e6e4aab909e71b627d82589d2640f803dd9 and https://github.com/clibs/libuv/commit/758dc25c8e645e3cf9344ce24b576db23a48d1c5, but still has a little problem with clib and libuv, they are conflicting while installing.

**Comment by yorkie** [comment]
using https://github.com/clibs/uv as the dependencies, thank you @jwerle
